param(
    [string]$Python = "python"
)

$root = Split-Path -Parent $PSScriptRoot
$reqPath = Join-Path $root "requirements.txt"
$outPath = Join-Path $root "requirements.lock.txt"

if (-not (Test-Path $reqPath)) {
    Write-Error "requirements.txt not found at $reqPath"
    exit 1
}

$reqs = Get-Content $reqPath |
    ForEach-Object { $_.Trim() } |
    Where-Object { $_ -and -not $_.StartsWith("#") } |
    ForEach-Object { $_ -replace "[<>=].*$", "" } |
    ForEach-Object { $_.Trim() }

$freeze = & $Python -m pip freeze 2>$null
if ($LASTEXITCODE -ne 0 -or -not $freeze) {
    Write-Error "Failed to run $Python -m pip freeze. Pass -Python with a full path if needed."
    exit 1
}

$map = @{}
foreach ($line in $freeze) {
    if ($line -match "^([^=]+)==(.+)$") {
        $map[$matches[1].ToLower()] = $line
    }
}

$lines = @()
$lines += "# Pinned dependencies for Project Confluence"
$lines += "# Generated by scripts/pin_requirements.ps1"
$lines += "# Date: " + (Get-Date -Format "yyyy-MM-dd")

$missing = @()
foreach ($r in $reqs) {
    $key = $r.ToLower()
    if ($map.ContainsKey($key)) {
        $lines += $map[$key]
    } else {
        $missing += $r
    }
}

if ($missing.Count -gt 0) {
    $lines += ""
    $lines += "# Missing (not installed during pinning): " + ($missing -join ", ")
}

$lines | Set-Content -Path $outPath -Encoding utf8
