# -*- coding: utf-8 -*-
"""
ML Archetype Classifier — Project Confluence
==============================================

Replaces the naive centroid-distance archetype classifier with trained
Decision Tree + Random Forest ensemble classifiers. Inspired by the
disease-prediction-ml approach (binary feature matrix → ensemble classifier).

Architecture:
    1. Generate synthetic training data from ODE simulations with varied params
    2. Engineer features beyond raw 5D Φ (coupling deficit, imbalance, etc.)
    3. Train DT + RF classifiers on labeled Φ feature vectors
    4. Classify new profiles with RF probability as confidence score

Usage:
    from models.ml_classifier import ArchetypeMLClassifier
    clf = ArchetypeMLClassifier()
    clf.train()
    archetype, confidence, method = clf.classify(phi_profile)
"""

import numpy as np
import warnings
import json
import os
from typing import Tuple, Optional, Dict, List
from dataclasses import dataclass

# Try to import sklearn — graceful fallback if not available
try:
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import cross_val_score, StratifiedKFold
    from sklearn.preprocessing import LabelEncoder
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

# Try joblib for model persistence
try:
    import joblib
    JOBLIB_AVAILABLE = True
except ImportError:
    JOBLIB_AVAILABLE = False


# ═══════════════════════════════════════════════════════════════════════════
# EXPANDED ARCHETYPES (4 → 8)
# ═══════════════════════════════════════════════════════════════════════════

ARCHETYPES = [
    "Healthy Complex",
    "Chaotic/Decoupled",
    "Rigid/Locked",
    "Collapsed/Exhausted",
    "Warburg Metabolic",
    "Immune Evasion",
    "Transitional/Pre-disease",
    "Mixed Pathology",
]

# Archetype centroid definitions in 5D Φ-space
# [Φ_temporal, Φ_spatial, Φ_functional, Φ_informational, Φ_coupling]
ARCHETYPE_CENTROIDS = {
    "Healthy Complex":       np.array([0.60, 0.55, 0.75, 0.45, 0.60]),
    "Chaotic/Decoupled":     np.array([0.80, 0.70, 0.30, 0.80, 0.15]),
    "Rigid/Locked":          np.array([0.15, 0.20, 0.20, 0.30, 0.85]),
    "Collapsed/Exhausted":   np.array([0.10, 0.10, 0.10, 0.10, 0.10]),
    "Warburg Metabolic":     np.array([0.35, 0.35, 0.90, 0.65, 0.30]),
    "Immune Evasion":        np.array([0.40, 0.30, 0.80, 0.50, 0.20]),
    "Transitional/Pre-disease": np.array([0.50, 0.45, 0.65, 0.50, 0.45]),
    "Mixed Pathology":       np.array([0.55, 0.50, 0.50, 0.70, 0.35]),
}


# ═══════════════════════════════════════════════════════════════════════════
# FEATURE ENGINEERING
# ═══════════════════════════════════════════════════════════════════════════

def engineer_features(phi_vector: np.ndarray, memory_features: Optional[Dict[str, float]] = None) -> np.ndarray:
    """
    Engineer extended feature set from a raw 5D Φ vector and memory layer.

    Input: [Φ_temporal, Φ_spatial, Φ_functional, Φ_informational, Φ_coupling]
    Output: 19D feature vector
    """
    v = np.asarray(phi_vector, dtype=float)

    magnitude = float(np.linalg.norm(v))
    mean_val = float(np.mean(v))
    variance = float(np.var(v))
    coupling_deficit = abs(v[4] - 0.55)
    ti_imbalance = abs(v[0] - v[3])
    func_dominance = v[2] - np.mean([v[0], v[1], v[3], v[4]])
    metab_sig = v[3] / (v[4] + 1e-6)

    m = memory_features or {}
    s_edges = m.get("structural_total_edges", 0.0)
    s_weight = m.get("structural_total_weight", 0.0)
    s_max = m.get("structural_max_weight", 0.0)
    s_dens = m.get("structural_edge_density", 0.0)
    s_avg = m.get("structural_average_weight", 0.0)
    t_events = m.get("temporal_total_events", 0.0)
    t_freq = m.get("temporal_event_frequency", 0.0)

    return np.array([
        v[0], v[1], v[2], v[3], v[4],
        magnitude, mean_val, variance,
        coupling_deficit, ti_imbalance,
        func_dominance, metab_sig,
        s_edges, s_weight, s_max, s_dens, s_avg,
        t_events, t_freq
    ])


# ═══════════════════════════════════════════════════════════════════════════
# SYNTHETIC TRAINING DATA GENERATOR
# ═══════════════════════════════════════════════════════════════════════════

def generate_training_data(
    n_per_class: int = 300,
    noise_std: float = 0.08,
    seed: int = 42,
) -> Tuple[np.ndarray, np.ndarray, List[str]]:
    """
    Generate synthetic training data by sampling around archetype centroids.

    Each archetype gets n_per_class samples generated by adding Gaussian noise
    to the centroid, then clipping to [0, 1]. Feature engineering is applied
    to each sample.

    Parameters
    ----------
    n_per_class : int
        Samples per archetype class.
    noise_std : float
        Standard deviation of Gaussian noise added to centroids.
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    X : ndarray, shape (n_per_class * 8, 19)
        Engineered feature matrix.
    y : ndarray, shape (n_per_class * 8,)
        Integer labels.
    class_names : list of str
        Archetype names corresponding to integer labels.
    """
    rng = np.random.RandomState(seed)
    X_raw = []
    y = []
    memory_features_list = []
    class_names = list(ARCHETYPE_CENTROIDS.keys())

    for label_idx, (name, centroid) in enumerate(ARCHETYPE_CENTROIDS.items()):
        for _ in range(n_per_class):
            # Add noise with class-specific variance scaling
            noise = rng.randn(5) * noise_std

            # Add extra variance for certain dimensions per class
            if name == "Warburg Metabolic":
                noise[2] *= 0.5   # Functional stays high (less noise)
                noise[3] *= 1.3   # More informational variance
            elif name == "Immune Evasion":
                noise[4] *= 0.5   # Coupling stays low
            elif name == "Transitional/Pre-disease":
                noise *= 1.5      # More spread (harder to classify = realistic)
            elif name == "Mixed Pathology":
                noise *= 1.3      # Also more spread

            sample = np.clip(centroid + noise, 0.0, 1.0)
            X_raw.append(sample)
            y.append(label_idx)
            
            # Simulate memory features based on archetype
            memory_features = {
                "structural_total_edges": rng.uniform(5, 50) if "Rigid" in name else rng.uniform(0, 20),
                "structural_total_weight": rng.uniform(10, 100),
                "structural_max_weight": rng.uniform(1, 10),
                "structural_edge_density": rng.uniform(0.5, 0.9) if "Rigid" in name else rng.uniform(0.1, 0.5),
                "structural_average_weight": rng.uniform(0.5, 5.0),
                "temporal_total_events": rng.uniform(20, 100) if "Chaotic" in name else rng.uniform(1, 20),
                "temporal_event_frequency": rng.uniform(0.5, 5.0) if "Chaotic" in name else rng.uniform(0.01, 0.5)
            }
            memory_features_list.append(memory_features)

    X_raw = np.array(X_raw)
    y = np.array(y)

    # Apply feature engineering
    X = np.array([engineer_features(row, mem) for row, mem in zip(X_raw, memory_features_list)])

    return X, y, class_names


# ═══════════════════════════════════════════════════════════════════════════
# ML ARCHETYPE CLASSIFIER
# ═══════════════════════════════════════════════════════════════════════════

class ArchetypeMLClassifier:
    """
    ML-based archetype classifier using Decision Tree + Random Forest.

    Trains on synthetic Φ data with 8 expanded archetypes. Falls back to
    centroid-distance if scikit-learn is not available.

    Usage:
        clf = ArchetypeMLClassifier()
        clf.train()
        archetype, confidence, method = clf.classify(phi_profile)
    """

    def __init__(self, verbose: bool = False):
        self.verbose = verbose
        self._dt = None
        self._rf = None
        self._class_names = None
        self._trained = False
        self._cv_accuracy = None

        if SKLEARN_AVAILABLE:
            self._dt = DecisionTreeClassifier(
                max_depth=8,
                min_samples_split=5,
                min_samples_leaf=3,
                random_state=42,
            )
            self._rf = RandomForestClassifier(
                n_estimators=100,
                max_depth=10,
                min_samples_split=4,
                min_samples_leaf=2,
                random_state=42,
                n_jobs=-1,
            )

    @property
    def is_available(self) -> bool:
        """Check if ML classification is available."""
        return SKLEARN_AVAILABLE and self._trained

    def train(self, n_per_class: int = 300, noise_std: float = 0.08) -> Dict:
        """
        Train the classifier on synthetic data.

        Returns
        -------
        report : dict
            Training report with accuracy metrics.
        """
        if not SKLEARN_AVAILABLE:
            return {"error": "scikit-learn not installed", "method": "centroid_fallback"}

        X, y, self._class_names = generate_training_data(
            n_per_class=n_per_class,
            noise_std=noise_std,
        )

        # Train both classifiers
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            self._dt.fit(X, y)
            self._rf.fit(X, y)

        # Cross-validation score
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        rf_scores = cross_val_score(self._rf, X, y, cv=cv, scoring="accuracy")
        dt_scores = cross_val_score(self._dt, X, y, cv=cv, scoring="accuracy")

        self._cv_accuracy = {
            "rf_mean": round(float(np.mean(rf_scores)), 4),
            "rf_std": round(float(np.std(rf_scores)), 4),
            "dt_mean": round(float(np.mean(dt_scores)), 4),
            "dt_std": round(float(np.std(dt_scores)), 4),
        }
        self._trained = True

        report = {
            "status": "trained",
            "n_samples": len(y),
            "n_classes": len(self._class_names),
            "classes": self._class_names,
            "cv_accuracy": self._cv_accuracy,
            "n_features": X.shape[1],
        }

        if self.verbose:
            print(f"  ML Classifier trained: RF={self._cv_accuracy['rf_mean']:.1%} "
                  f"(±{self._cv_accuracy['rf_std']:.1%}), "
                  f"DT={self._cv_accuracy['dt_mean']:.1%} "
                  f"(±{self._cv_accuracy['dt_std']:.1%})")
            print(f"  Classes: {self._class_names}")

        return report

    def train_on_external_data(self, X: np.ndarray, y: np.ndarray,
                                class_names: List[str]) -> Dict:
        """
        Train on externally provided feature matrix and labels.

        Used by pathology_integrator to train on real ODE-derived data.
        """
        if not SKLEARN_AVAILABLE:
            return {"error": "scikit-learn not installed"}

        self._class_names = class_names

        # Reinitialize classifiers
        self._dt = DecisionTreeClassifier(
            max_depth=8, min_samples_split=5, min_samples_leaf=3, random_state=42)
        self._rf = RandomForestClassifier(
            n_estimators=100, max_depth=10, min_samples_split=4,
            min_samples_leaf=2, random_state=42, n_jobs=-1)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            self._dt.fit(X, y)
            self._rf.fit(X, y)

        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        rf_scores = cross_val_score(self._rf, X, y, cv=cv, scoring="accuracy")
        dt_scores = cross_val_score(self._dt, X, y, cv=cv, scoring="accuracy")

        self._cv_accuracy = {
            "rf_mean": round(float(np.mean(rf_scores)), 4),
            "rf_std": round(float(np.std(rf_scores)), 4),
            "dt_mean": round(float(np.mean(dt_scores)), 4),
            "dt_std": round(float(np.std(dt_scores)), 4),
        }
        self._trained = True

        report = {
            "status": "trained_on_external_data",
            "n_samples": len(y),
            "n_classes": len(class_names),
            "cv_accuracy": self._cv_accuracy,
            "n_features": X.shape[1],
        }

        if self.verbose:
            print(f"  Trained on external data: RF={self._cv_accuracy['rf_mean']:.1%} "
                  f"(+/-{self._cv_accuracy['rf_std']:.1%})")

        return report

    def classify(self, phi) -> Tuple[str, float, str]:
        """
        Classify a PhiProfile or raw Φ vector.

        Parameters
        ----------
        phi : PhiProfile or ndarray
            Either a PhiProfile dataclass or a 5D numpy array.

        Returns
        -------
        archetype : str
            Predicted archetype name.
        confidence : float
            Classification confidence (0-1).
        method : str
            "random_forest", "decision_tree", or "centroid_fallback"
        """
        # Extract Φ vector
        if hasattr(phi, 'phi_vector'):
            v = phi.phi_vector
            memory = getattr(phi, 'memory_features', {})
        elif isinstance(phi, np.ndarray):
            v = phi
            memory = {}
        else:
            v = np.array(phi)
            memory = {}

        # Try ML classification first
        if self.is_available:
            features = engineer_features(v, memory).reshape(1, -1)

            # Use Random Forest (more robust)
            rf_pred = self._rf.predict(features)[0]
            rf_proba = self._rf.predict_proba(features)[0]
            confidence = float(np.max(rf_proba))
            archetype = self._class_names[rf_pred]

            return archetype, round(confidence, 4), "random_forest"

        # Fallback: expanded centroid distance
        return self._centroid_classify(v)

    def _centroid_classify(self, v: np.ndarray) -> Tuple[str, float, str]:
        """Fallback centroid-distance classification with expanded archetypes."""
        distances = {
            name: float(np.linalg.norm(v - centroid))
            for name, centroid in ARCHETYPE_CENTROIDS.items()
        }
        best = min(distances, key=distances.get)
        max_possible = np.sqrt(5)
        confidence = 1.0 - (distances[best] / max_possible)
        return best, round(confidence, 4), "centroid_fallback"

    def classify_with_details(self, phi) -> Dict:
        """
        Classify with full probability distribution across all archetypes.

        Returns dict with prediction, probabilities, and feature values.
        """
        if hasattr(phi, 'phi_vector'):
            v = phi.phi_vector
            memory = getattr(phi, 'memory_features', {})
        elif isinstance(phi, np.ndarray):
            v = phi
            memory = {}
        else:
            v = np.array(phi)
            memory = {}

        features = engineer_features(v, memory)
        result = {
            "features": {
                "phi_vector": v.tolist(),
                "magnitude": float(features[5]),
                "mean": float(features[6]),
                "variance": float(features[7]),
                "coupling_deficit": float(features[8]),
                "ti_imbalance": float(features[9]),
                "func_dominance": float(features[10]),
                "metab_signature": float(features[11]),
                "structural_total_edges": float(features[12]),
                "structural_total_weight": float(features[13]),
                "structural_max_weight": float(features[14]),
                "structural_edge_density": float(features[15]),
                "structural_average_weight": float(features[16]),
                "temporal_total_events": float(features[17]),
                "temporal_event_frequency": float(features[18]),
            },
        }

        if self.is_available:
            rf_proba = self._rf.predict_proba(features.reshape(1, -1))[0]
            dt_pred = self._dt.predict(features.reshape(1, -1))[0]

            proba_dict = {
                self._class_names[i]: round(float(p), 4)
                for i, p in enumerate(rf_proba)
            }
            sorted_proba = dict(sorted(proba_dict.items(), key=lambda x: -x[1]))

            result["prediction"] = self._class_names[np.argmax(rf_proba)]
            result["confidence"] = round(float(np.max(rf_proba)), 4)
            result["probabilities"] = sorted_proba
            result["dt_prediction"] = self._class_names[dt_pred]
            result["agreement"] = result["prediction"] == result["dt_prediction"]
            result["method"] = "random_forest"
        else:
            arch, conf, method = self._centroid_classify(v)
            result["prediction"] = arch
            result["confidence"] = conf
            result["method"] = method

        return result

    def save(self, path: str):
        """Save trained model to disk."""
        if not self._trained:
            raise RuntimeError("Model not trained — call train() first")
        if not JOBLIB_AVAILABLE:
            raise RuntimeError("joblib not installed — cannot save model")

        data = {
            "dt": self._dt,
            "rf": self._rf,
            "class_names": self._class_names,
            "cv_accuracy": self._cv_accuracy,
        }
        joblib.dump(data, path)

    def load(self, path: str):
        """Load trained model from disk."""
        if not JOBLIB_AVAILABLE:
            raise RuntimeError("joblib not installed — cannot load model")
        if not os.path.exists(path):
            raise FileNotFoundError(f"Model file not found: {path}")

        data = joblib.load(path)
        self._dt = data["dt"]
        self._rf = data["rf"]
        self._class_names = data["class_names"]
        self._cv_accuracy = data.get("cv_accuracy")
        self._trained = True


# ═══════════════════════════════════════════════════════════════════════════
# SINGLETON INSTANCE (auto-train on first use)
# ═══════════════════════════════════════════════════════════════════════════

_default_classifier = None


def get_classifier(verbose: bool = False) -> ArchetypeMLClassifier:
    """Get or create the default ML classifier (trains on first call)."""
    global _default_classifier
    if _default_classifier is None:
        _default_classifier = ArchetypeMLClassifier(verbose=verbose)
        _default_classifier.train()
    return _default_classifier


# ═══════════════════════════════════════════════════════════════════════════
# CLI SMOKE TEST
# ═══════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("=" * 60)
    print("  ML Archetype Classifier — Smoke Test")
    print("=" * 60)

    clf = ArchetypeMLClassifier(verbose=True)
    report = clf.train()
    print(f"\n  Training report: {json.dumps(report, indent=2)}")

    # Test classification on known archetypes
    test_cases = {
        "Healthy":     np.array([0.60, 0.55, 0.75, 0.45, 0.60]),
        "Cancer/TNBC": np.array([0.33, 0.33, 0.99, 0.65, 0.47]),
        "Collapsed":   np.array([0.05, 0.08, 0.12, 0.06, 0.09]),
        "Chaotic":     np.array([0.82, 0.68, 0.25, 0.85, 0.12]),
        "Warburg":     np.array([0.35, 0.30, 0.92, 0.60, 0.25]),
    }

    print(f"\n  {'Test Case':<16} {'Prediction':<25} {'Confidence':>10} {'Method':<18}")
    print(f"  {'-'*16} {'-'*25} {'-'*10} {'-'*18}")

    for name, phi_vec in test_cases.items():
        arch, conf, method = clf.classify(phi_vec)
        print(f"  {name:<16} {arch:<25} {conf:>10.1%} {method:<18}")

    # Detailed classification for TNBC
    print(f"\n  ── Detailed TNBC Classification ──")
    details = clf.classify_with_details(test_cases["Cancer/TNBC"])
    for arch, prob in list(details["probabilities"].items())[:4]:
        print(f"  {arch:<25} {prob:>8.1%}")
    print(f"  DT agrees: {details['agreement']}")
