# -*- coding: utf-8 -*-
"""
Neural Therapy Brain — Project Confluence
=========================================

A compact recurrent neural controller (a "small brain") whose *neurons are
trained on therapy datasets* to keep the complex cancer environment under
therapeutic control — suppressing the resistant clone and holding tumour
burden near a healthy attractor — **despite ambivalent externalities**
(biological uncertainty, measurement noise, and inter-patient variability).

Where the hand-crafted ``AdaptiveController`` encodes a fixed policy
π(state) → dose, this module *learns* that policy with a recurrent network:

    observation history ──► GRU "brain" ──► raw dose ──► SAFETY LAYER ──► dose

The safety layer is the same non-overridable "assurance layer" used by
``AdaptiveController`` (absolute dose cap, forced drug holidays, cumulative
toxicity budget, Nigeria NSTG 2022 layer), so a learned policy can never
violate the hard clinical bounds.

────────────────────────────────────────────────────────────────────────────
DATA & VALIDATION DISCLAIMER
────────────────────────────────────────────────────────────────────────────
By default the brain is trained on **synthetic** trajectories generated by the
repository's mechanistic clonal-dynamics simulator under the robust adaptive
expert policy. Real longitudinal clinical datasets can be plugged in via
``TherapyDataset.from_real_cohort`` — but real-data training is **pending** and
MUST be subject to independent expert review and authentic clinical validation
before any translational interpretation. This is a research artifact only, not
a medical device or clinical decision-support tool. See ``DISCLAIMER.md``.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from .clonal_dynamics import (
    ClonalDynamicsEngine,
    ClonalParams,
    get_cancer_specific_clonal_params,
)
from .resistance_model import ResistanceTracker, ResistanceParams
from .adaptive_controller import AdaptiveController, PolicyMode, PolicyParams

# ── Optional torch import (graceful degradation) ────────────────────────────
try:
    import torch
    import torch.nn as nn

    TORCH_AVAILABLE = True
except ImportError:  # pragma: no cover - exercised only without torch
    TORCH_AVAILABLE = False

    class _DummyModule:  # noqa: D401 - minimal stand-in
        pass

    class nn:  # type: ignore
        Module = _DummyModule


# Number of scalar features fed to the brain at each timestep.
OBS_DIM = 6


# ═══════════════════════════════════════════════════════════════════════════
# OBSERVATION ENCODING
# ═══════════════════════════════════════════════════════════════════════════

def encode_observation(
    sensitive: float,
    resistant: float,
    carrying_capacity: float,
    efficacy: float,
    toxicity_fraction: float,
    is_dosing: bool,
    last_dose: float,
) -> List[float]:
    """Map the raw biological + controller state to the brain's input vector.

    All features are kept in roughly ``[0, 1]`` so the network sees a
    well-conditioned input without an external scaler.
    """
    total = sensitive + resistant
    v_frac = total / carrying_capacity if carrying_capacity > 0 else 0.0
    r_frac = resistant / total if total > 1e-10 else 0.0
    return [
        float(np.clip(v_frac, 0.0, 2.0)),
        float(np.clip(r_frac, 0.0, 1.0)),
        float(np.clip(efficacy, 0.0, 1.0)),
        float(np.clip(toxicity_fraction, 0.0, 1.5)),
        1.0 if is_dosing else 0.0,
        float(np.clip(last_dose, 0.0, 1.0)),
    ]


# ═══════════════════════════════════════════════════════════════════════════
# THE BRAIN (recurrent policy network)
# ═══════════════════════════════════════════════════════════════════════════

class NeuralTherapyBrain(nn.Module):
    """A small GRU-based recurrent dosing policy.

    Intentionally compact (a "fly brain"): a single-layer GRU plus a linear
    read-out head. The recurrent hidden state gives the controller memory of
    the trajectory so far, which is what lets it react to *trends* (e.g. a
    rising resistant fraction) rather than only the instantaneous state.

    Output is squashed to ``[0, max_dose]`` so the raw network action already
    respects the absolute dose cap before the safety layer runs.
    """

    def __init__(
        self,
        obs_dim: int = OBS_DIM,
        hidden_dim: int = 32,
        max_dose: float = 0.9,
    ):
        if not TORCH_AVAILABLE:
            raise ImportError(
                "PyTorch is required for NeuralTherapyBrain. Install it with "
                "`pip install torch` (CPU build is sufficient)."
            )
        super().__init__()
        self.obs_dim = obs_dim
        self.hidden_dim = hidden_dim
        self.max_dose = float(max_dose)
        self.gru = nn.GRUCell(obs_dim, hidden_dim)
        self.head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, 1),
        )

    # -- sequence forward (training) ----------------------------------------
    def forward(self, obs_seq: "torch.Tensor") -> "torch.Tensor":
        """Run the brain over a batch of observation sequences.

        Args:
            obs_seq: ``[batch, seq_len, obs_dim]``.

        Returns:
            doses: ``[batch, seq_len]`` in ``[0, max_dose]``.
        """
        batch, seq_len, _ = obs_seq.shape
        h = torch.zeros(batch, self.hidden_dim, dtype=obs_seq.dtype, device=obs_seq.device)
        outputs = []
        for t in range(seq_len):
            h = self.gru(obs_seq[:, t, :], h)
            outputs.append(self.head(h))
        doses = torch.sigmoid(torch.stack(outputs, dim=1).squeeze(-1)) * self.max_dose
        return doses

    # -- single step (online closed-loop deployment) ------------------------
    def step(
        self,
        obs: List[float],
        hidden: Optional["torch.Tensor"] = None,
    ) -> Tuple[float, "torch.Tensor"]:
        """Advance the brain one timestep, carrying its recurrent memory."""
        with torch.no_grad():
            x = torch.tensor(obs, dtype=torch.float32).unsqueeze(0)
            if hidden is None:
                hidden = torch.zeros(1, self.hidden_dim, dtype=torch.float32)
            hidden = self.gru(x, hidden)
            raw = torch.sigmoid(self.head(hidden)).item() * self.max_dose
        return float(raw), hidden


# ═══════════════════════════════════════════════════════════════════════════
# DATASETS — synthetic expert rollouts + real-cohort hook
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class TherapyDataset:
    """Sequences of (observation, target-dose) used to train the brain.

    ``observations``: ``[N, seq_len, OBS_DIM]``
    ``target_doses``: ``[N, seq_len]``
    ``source``:       provenance string (e.g. ``"synthetic_expert"``).
    ``validated``:    whether the data has passed clinical validation. Real
                      cohorts start ``False`` and gate any downstream use.
    """

    observations: np.ndarray
    target_doses: np.ndarray
    source: str = "synthetic_expert"
    validated: bool = False
    meta: Dict = field(default_factory=dict)

    def __len__(self) -> int:
        return int(self.observations.shape[0])

    def to_tensors(self) -> Tuple["torch.Tensor", "torch.Tensor"]:
        if not TORCH_AVAILABLE:
            raise ImportError("PyTorch is required to materialize dataset tensors.")
        return (
            torch.tensor(self.observations, dtype=torch.float32),
            torch.tensor(self.target_doses, dtype=torch.float32),
        )

    # -- REAL DATA HOOK (pending expert review + clinical validation) --------
    @classmethod
    def from_real_cohort(cls, path: str, require_validated: bool = True) -> "TherapyDataset":
        """Load a real longitudinal cohort for training.

        Expected JSON schema (one entry per patient)::

            {
              "validated": false,
              "dt_days": 1.0,
              "carrying_capacity": 1.0,
              "patients": [
                {
                  "id": "PT-001",
                  "steps": [
                    {"sensitive": 0.8, "resistant": 0.2, "efficacy": 1.0,
                     "toxicity_fraction": 0.0, "dose": 0.0}, ...
                  ]
                }, ...
              ]
            }

        SAFETY: real clinical data must be de-identified and independently
        validated. Unless ``require_validated=False`` is explicitly passed,
        this refuses to return unvalidated data so that experimental cohorts
        cannot be silently used to train a dosing policy.
        """
        payload = json.loads(Path(path).read_text())
        validated = bool(payload.get("validated", False))
        if require_validated and not validated:
            raise ValueError(
                f"Refusing to load unvalidated real cohort '{path}'. Real-data "
                "training is pending independent expert review and authentic "
                "clinical validation. Pass require_validated=False only for "
                "clearly-labelled research experiments."
            )

        K = float(payload.get("carrying_capacity", 1.0))
        seqs, doses = [], []
        for patient in payload.get("patients", []):
            steps = patient.get("steps", [])
            obs_rows, dose_rows = [], []
            last_dose = 0.0
            for s in steps:
                obs_rows.append(
                    encode_observation(
                        sensitive=float(s.get("sensitive", 0.0)),
                        resistant=float(s.get("resistant", 0.0)),
                        carrying_capacity=K,
                        efficacy=float(s.get("efficacy", 1.0)),
                        toxicity_fraction=float(s.get("toxicity_fraction", 0.0)),
                        is_dosing=last_dose > 0.0,
                        last_dose=last_dose,
                    )
                )
                dose_rows.append(float(s.get("dose", 0.0)))
                last_dose = float(s.get("dose", 0.0))
            if obs_rows:
                seqs.append(obs_rows)
                doses.append(dose_rows)

        if not seqs:
            raise ValueError(f"No usable patient sequences found in '{path}'.")

        # Pad ragged sequences to a common length.
        max_len = max(len(s) for s in seqs)
        obs_arr = np.zeros((len(seqs), max_len, OBS_DIM), dtype=np.float32)
        dose_arr = np.zeros((len(seqs), max_len), dtype=np.float32)
        for i, (s, d) in enumerate(zip(seqs, doses)):
            obs_arr[i, : len(s), :] = np.asarray(s, dtype=np.float32)
            dose_arr[i, : len(d)] = np.asarray(d, dtype=np.float32)

        return cls(
            observations=obs_arr,
            target_doses=dose_arr,
            source=f"real_cohort:{Path(path).name}",
            validated=validated,
            meta={"n_patients": len(seqs), "seq_len": max_len},
        )


def sample_uncertain_params(base: ClonalParams, rng: np.random.RandomState) -> ClonalParams:
    """Draw a perturbed parameter set — the "ambivalent externalities".

    Multiplicative jitter on growth, kill, competition, and noise terms plus a
    resampled pre-existing resistant fraction models inter-patient biological
    variability and our uncertainty about it.
    """
    p = ClonalParams(**base.__dict__)

    def jitter(scale: float) -> float:
        return float(np.exp(rng.normal(0.0, scale)))

    p.sensitive_growth_rate *= jitter(0.25)
    p.resistant_growth_rate *= jitter(0.25)
    p.drug_kill_rate_sensitive *= jitter(0.30)
    p.drug_kill_rate_resistant *= jitter(0.30)
    p.alpha_RS *= jitter(0.15)
    p.alpha_SR *= jitter(0.15)
    p.resistance_fitness_cost *= jitter(0.20)
    p.noise_scale *= jitter(0.40)
    p.resistant_initial = float(np.clip(base.resistant_initial * jitter(0.35), 0.02, 0.5))
    p.sensitive_initial = float(np.clip(1.0 - p.resistant_initial, 0.5, 0.98))
    return p


def _rollout_expert(
    params: ClonalParams,
    total_days: float,
    dt: float,
    seed: int,
) -> Tuple[np.ndarray, np.ndarray]:
    """Roll out the robust adaptive expert; record (obs, dose) each step."""
    engine = ClonalDynamicsEngine(params)
    resistance = ResistanceTracker(ResistanceParams())
    resistance.initialize_drugs(["primary_agent"])
    expert = AdaptiveController(policy_mode=PolicyMode.ROBUST_ADAPTIVE)

    n_steps = int(total_days / dt)
    obs_rows, dose_rows = [], []
    last_dose = 0.0
    for i in range(n_steps):
        state = engine.state
        efficacy = resistance.get_efficacy_factor("primary_agent")
        tox_frac = expert.ctrl_state.cumulative_toxicity / (
            expert.params.max_cumulative_toxicity + 1e-10
        )
        obs = encode_observation(
            sensitive=state.sensitive,
            resistant=state.resistant,
            carrying_capacity=params.carrying_capacity,
            efficacy=efficacy,
            toxicity_fraction=tox_frac,
            is_dosing=expert.ctrl_state.is_dosing,
            last_dose=last_dose,
        )
        dose = expert.decide(
            sensitive=state.sensitive,
            resistant=state.resistant,
            carrying_capacity=params.carrying_capacity,
            dt=dt,
            resistance_efficacy=efficacy,
        )
        obs_rows.append(obs)
        dose_rows.append(dose)
        last_dose = dose

        engine.step(
            dt=dt,
            drug_active=(dose > 0),
            drug_pressure=dose,
            phase="flatten" if dose > 0.5 else "heat" if dose == 0 else "push",
            seed=seed + i,
        )
        resistance.update(dt, ["primary_agent"] if dose > 0 else [])

    return np.asarray(obs_rows, dtype=np.float32), np.asarray(dose_rows, dtype=np.float32)


def generate_expert_dataset(
    cancer_types: Optional[List[str]] = None,
    n_scenarios: int = 60,
    total_days: float = 60.0,
    dt: float = 0.5,
    seed: int = 0,
) -> TherapyDataset:
    """Build a training dataset by cloning the robust adaptive expert across
    many randomized (uncertain) biological scenarios.

    This is the "medical dataset" the brain's neurons are trained on. Each
    scenario perturbs the mechanistic parameters (:func:`sample_uncertain_params`)
    so the learned policy must generalise across the uncertainty set rather
    than memorise a single patient.
    """
    cancer_types = cancer_types or ["NSCLC", "TNBC", "GBM", "AML", "CRC", "PDAC"]
    rng = np.random.RandomState(seed)
    seq_len = int(total_days / dt)

    obs_all = np.zeros((n_scenarios, seq_len, OBS_DIM), dtype=np.float32)
    dose_all = np.zeros((n_scenarios, seq_len), dtype=np.float32)

    for i in range(n_scenarios):
        ctype = cancer_types[i % len(cancer_types)]
        base = get_cancer_specific_clonal_params(ctype)
        params = sample_uncertain_params(base, rng)
        obs, dose = _rollout_expert(params, total_days, dt, seed=1000 + i * 17)
        obs_all[i] = obs
        dose_all[i] = dose

    return TherapyDataset(
        observations=obs_all,
        target_doses=dose_all,
        source="synthetic_expert",
        validated=True,  # synthetic data is safe to train on
        meta={
            "n_scenarios": n_scenarios,
            "seq_len": seq_len,
            "dt": dt,
            "total_days": total_days,
            "cancer_types": cancer_types,
        },
    )


# ═══════════════════════════════════════════════════════════════════════════
# TRAINING (behavioral cloning)
# ═══════════════════════════════════════════════════════════════════════════

def train_brain(
    dataset: TherapyDataset,
    hidden_dim: int = 32,
    max_dose: float = 0.9,
    epochs: int = 60,
    lr: float = 5e-3,
    val_fraction: float = 0.2,
    seed: int = 0,
    verbose: bool = False,
) -> Tuple[NeuralTherapyBrain, Dict]:
    """Train the brain to imitate the expert dosing signal (behavioral cloning).

    Returns the trained model and a history dict with per-epoch train/val loss.
    """
    if not TORCH_AVAILABLE:
        raise ImportError("PyTorch is required to train the NeuralTherapyBrain.")

    torch.manual_seed(seed)
    obs, doses = dataset.to_tensors()

    n = obs.shape[0]
    perm = torch.randperm(n, generator=torch.Generator().manual_seed(seed))
    obs, doses = obs[perm], doses[perm]
    n_val = max(1, int(n * val_fraction))
    tr_obs, tr_dose = obs[n_val:], doses[n_val:]
    va_obs, va_dose = obs[:n_val], doses[:n_val]

    model = NeuralTherapyBrain(obs_dim=obs.shape[-1], hidden_dim=hidden_dim, max_dose=max_dose)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.MSELoss()

    history = {"train_loss": [], "val_loss": []}
    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        pred = model(tr_obs)
        loss = loss_fn(pred, tr_dose)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.step()

        model.eval()
        with torch.no_grad():
            val_loss = loss_fn(model(va_obs), va_dose).item()

        history["train_loss"].append(float(loss.item()))
        history["val_loss"].append(float(val_loss))
        if verbose and (epoch % 10 == 0 or epoch == epochs - 1):
            print(f"  epoch {epoch:3d}  train={loss.item():.5f}  val={val_loss:.5f}")

    return model, history


# ═══════════════════════════════════════════════════════════════════════════
# CLOSED-LOOP DEPLOYMENT (brain + hard safety layer)
# ═══════════════════════════════════════════════════════════════════════════

class NeuralBrainController:
    """Deploys a trained brain in closed loop, wrapped by the assurance layer.

    The brain proposes a raw dose; the same non-overridable safety constraints
    used by :class:`AdaptiveController` (dose cap, forced holidays, toxicity
    budget, Nigeria NSTG layer) are then applied, so a learned policy can never
    breach the hard clinical bounds.
    """

    def __init__(
        self,
        brain: NeuralTherapyBrain,
        policy_params: Optional[PolicyParams] = None,
        cancer_type: str = "NSCLC",
    ):
        self.brain = brain
        self.safety = AdaptiveController(
            policy_mode=PolicyMode.ROBUST_ADAPTIVE,
            policy_params=policy_params,
            cancer_type=cancer_type,
        )
        self._hidden = None
        self._last_dose = 0.0

    def reset(self):
        self.safety.reset()
        self._hidden = None
        self._last_dose = 0.0

    def decide(self, sensitive: float, resistant: float, carrying_capacity: float,
               dt: float, resistance_efficacy: float = 1.0) -> float:
        cs = self.safety.ctrl_state
        tox_frac = cs.cumulative_toxicity / (self.safety.params.max_cumulative_toxicity + 1e-10)
        obs = encode_observation(
            sensitive=sensitive,
            resistant=resistant,
            carrying_capacity=carrying_capacity,
            efficacy=resistance_efficacy,
            toxicity_fraction=tox_frac,
            is_dosing=cs.is_dosing,
            last_dose=self._last_dose,
        )
        raw_dose, self._hidden = self.brain.step(obs, self._hidden)

        # Assurance layer: identical hard constraints as AdaptiveController.
        dose = self.safety._apply_constraints(raw_dose, dt)
        self.safety._update_state(dose, (sensitive + resistant) / carrying_capacity,
                                  resistant / (sensitive + resistant + 1e-10), dt)
        self._last_dose = dose
        return dose

    def get_summary(self) -> Dict:
        summary = self.safety.get_summary()
        summary["policy_mode"] = "neural_brain"
        return summary


def run_neural_brain_simulation(
    brain: NeuralTherapyBrain,
    cancer_type: str = "NSCLC",
    total_days: float = 60.0,
    dt: float = 0.5,
    seed: int = 42,
    params: Optional[ClonalParams] = None,
) -> Dict:
    """Closed-loop simulation driven by the trained brain.

    Mirrors :func:`models.adaptive_controller.run_adaptive_simulation` so
    outcomes are directly comparable.
    """
    clonal_params = params or get_cancer_specific_clonal_params(cancer_type)
    engine = ClonalDynamicsEngine(clonal_params)
    resistance = ResistanceTracker(ResistanceParams())
    resistance.initialize_drugs(["primary_agent"])
    controller = NeuralBrainController(brain, cancer_type=cancer_type)

    n_steps = int(total_days / dt)
    for i in range(n_steps):
        state = engine.state
        efficacy = resistance.get_efficacy_factor("primary_agent")
        dose = controller.decide(
            sensitive=state.sensitive,
            resistant=state.resistant,
            carrying_capacity=clonal_params.carrying_capacity,
            dt=dt,
            resistance_efficacy=efficacy,
        )
        engine.step(
            dt=dt,
            drug_active=(dose > 0),
            drug_pressure=dose,
            phase="flatten" if dose > 0.5 else "heat" if dose == 0 else "push",
            seed=seed + i,
        )
        resistance.update(dt, ["primary_agent"] if dose > 0 else [])

    final_state = engine.state
    burden_arr = np.array(final_state.burden_trajectory)
    time_under_control = float(
        np.sum(burden_arr < 0.8 * clonal_params.carrying_capacity) * dt
    )
    outcome = {
        "final_burden": round(float(final_state.tumor_fraction), 6),
        "final_resistant_fraction": round(float(final_state.resistant_fraction), 4),
        "days_under_control": round(time_under_control, 1),
        "resistant_takeover": bool(final_state.resistant_fraction > 0.80),
    }
    return {
        "cancer_type": cancer_type,
        "total_days": total_days,
        "trajectories": {
            "time": final_state.time_points,
            "sensitive": final_state.sensitive_trajectory,
            "resistant": final_state.resistant_trajectory,
            "burden": final_state.burden_trajectory,
            "doses": controller.safety.ctrl_state.dose_history,
        },
        "controller_summary": controller.get_summary(),
        "outcome": outcome,
    }


def save_brain(model: NeuralTherapyBrain, path: str, meta: Optional[Dict] = None) -> None:
    """Persist a trained brain (weights + architecture hyperparameters)."""
    if not TORCH_AVAILABLE:
        raise ImportError("PyTorch is required to save the NeuralTherapyBrain.")
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "state_dict": model.state_dict(),
            "obs_dim": model.obs_dim,
            "hidden_dim": model.hidden_dim,
            "max_dose": model.max_dose,
            "meta": meta or {},
        },
        path,
    )


def load_brain(path: str) -> NeuralTherapyBrain:
    """Load a brain saved with :func:`save_brain`."""
    if not TORCH_AVAILABLE:
        raise ImportError("PyTorch is required to load the NeuralTherapyBrain.")
    ckpt = torch.load(path, map_location="cpu", weights_only=False)
    model = NeuralTherapyBrain(
        obs_dim=ckpt.get("obs_dim", OBS_DIM),
        hidden_dim=ckpt.get("hidden_dim", 32),
        max_dose=ckpt.get("max_dose", 0.9),
    )
    model.load_state_dict(ckpt["state_dict"])
    model.eval()
    return model


def evaluate_robustness(
    brain: NeuralTherapyBrain,
    cancer_types: Optional[List[str]] = None,
    n_scenarios: int = 40,
    total_days: float = 60.0,
    dt: float = 0.5,
    seed: int = 777,
) -> Dict:
    """Score the brain against MTD and the expert across randomized scenarios.

    This is the "ambivalent externalities" stress test: each scenario perturbs
    the biology, and we report how often each strategy loses to resistant
    takeover and how well it maintains control.
    """
    from .adaptive_controller import run_adaptive_simulation

    cancer_types = cancer_types or ["NSCLC", "TNBC", "GBM", "AML", "CRC", "PDAC"]
    rng = np.random.RandomState(seed)

    agg = {
        k: {"takeover": 0, "R_frac": [], "burden": [], "ctrl_days": []}
        for k in ("MTD", "Expert", "NeuralBrain")
    }

    mtd_params = PolicyParams(
        dose_on_threshold=0.0, dose_off_threshold=0.0, robust_max_dose=1.0,
        max_continuous_dose_days=999, min_holiday_days=0, max_cumulative_toxicity=999,
    )

    for i in range(n_scenarios):
        ctype = cancer_types[i % len(cancer_types)]
        base = get_cancer_specific_clonal_params(ctype)
        params = sample_uncertain_params(base, rng)
        s = seed + i * 31

        mtd = run_adaptive_simulation(ctype, PolicyMode.THRESHOLD, mtd_params,
                                      int(total_days), dt, s)
        expert = run_adaptive_simulation(ctype, PolicyMode.ROBUST_ADAPTIVE,
                                         None, int(total_days), dt, s)
        brain_res = run_neural_brain_simulation(brain, ctype, total_days, dt, s, params=params)

        for name, res in (("MTD", mtd), ("Expert", expert), ("NeuralBrain", brain_res)):
            o = res["outcome"]
            agg[name]["takeover"] += int(o["resistant_takeover"])
            agg[name]["R_frac"].append(o["final_resistant_fraction"])
            agg[name]["burden"].append(o["final_burden"])
            agg[name]["ctrl_days"].append(o["days_under_control"])

    report = {"n_scenarios": n_scenarios, "total_days": total_days, "strategies": {}}
    for name, d in agg.items():
        report["strategies"][name] = {
            "resistant_takeover_rate": round(d["takeover"] / n_scenarios, 4),
            "mean_final_resistant_fraction": round(float(np.mean(d["R_frac"])), 4),
            "mean_final_burden": round(float(np.mean(d["burden"])), 4),
            "mean_days_under_control": round(float(np.mean(d["ctrl_days"])), 2),
        }
    return report
